version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14-browsers
    working_directory: ~/repo
    shell: /bin/bash
    environment:
      NODE_ENV: test

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install playwright browsers
          command: npx playwright install
      - run:
          name: Run playwright tests in Chromium
          command: npx playwright test --project=chromium
      - run:
          name: Run playwright tests in Firefox
          command: npx playwright test --project=firefox
      - run:
          name: Run playwright tests in Webkit
          command: npx playwright test --project=webkit

workflows:
  test:
    jobs:
      - test