version: 2.1

executors:
  node-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.28.1-jammy
    working_directory: ~/repo
    shell: /bin/bash
    environment:
      NODE_ENV: test

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run playwright tests in Chromium
          command: npx playwright test --project=chromium
      - run:
          name: Run playwright tests in Firefox
          command: npx playwright test --project=firefox

workflows:
  test:
    jobs:
      - test